CREATE DATABASE "CableBI";

\connect "CableBI"

GRANT ALL PRIVILEGES ON DATABASE "CableBI" TO sulla;
GRANT USAGE, CREATE ON SCHEMA public TO sulla;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sulla;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sulla;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO sulla;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO sulla;
